version: '3.8'

services:
  toilex:
    build: .
    ports:
      - "3000:3000"  # React Router app port
      - "3001:3001"  # Socket.IO server port
    environment:
      # React Router app port (default: 3000)
      - PORT=3000
      # Socket.IO server port (default: PORT + 1 = 3001)
      - SOCKET_PORT=3001
      # Socket.IO server URL (used by frontend)
      - VITE_SOCKET_URL=http://localhost:3001
      # OpenAI API key (for Turd Analyzer feature)
      - OPENAI_API_KEY=your-openai-api-key-here
      # Optional: Custom OpenAI endpoint
      # - OPENAI_BASE_URL=https://api.openai.com/v1
    restart: unless-stopped

